### ISSUE TITLE
Error: Not supported at fetch

### ISSUE THREAD

**Issue by miggat** [KEGustafsson/signalk-vessels-to-ais#15]
Hello, I just installed the plugin on SignalK v.1.41.3, and I get this error on SignalK's log window:

Just after starting the plugin:

```
Mar 20 08:56:14 (node:13518) UnhandledPromiseRejectionWarning: Error: Not supported at fetch (/home/pi/.signalk/node_modules/signalk-vessels-to-ais/index.js:25:49) at fetch.then.catch (/home/pi/.signalk/node_modules/signalk-vessels-to-ais/index.js:77:9) at process._tickCallback (internal/process/next_tick.js:68:7)

Mar 20 08:56:14 (node:13518) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 369)
```

On every tick:

```
Mar 20 08:57:14 Error: Not supported at fetch (/home/pi/.signalk/node_modules/signalk-vessels-to-ais/index.js:25:49) at Timeout.readData [as _onTimeout] (/home/pi/.signalk/node_modules/signalk-vessels-to-ais/index.js:190:7) at ontimeout (timers.js:438:13) at tryOnTimeout (timers.js:300:5) at listOnTimeout (timers.js:263:5) at Timer.processTimers (timers.js:223:10)
```

I'm not using SSL, so added a catch() to the fetch() at line 78 and I get a "Not supported"  exception.

Not sure if I can try something else.

**Comment by KEGustafsson** [comment]
Hello and thanks for reporting this.

First I would like to know which Nodejs version (`node --version`) you are running and host or docker?

This seem to be related to node-fetch version change from v2.x to v3.x and how module is imported.
[Converted to ES Module](https://github.com/node-fetch/node-fetch/blob/HEAD/docs/v3-UPGRADE-GUIDE.md#converted-to-es-module)

**Comment by miggat** [comment]
Everything was installed from the OpenPlotter v2 image, and Node version is 10.24.0

I'm completely lost with Node, but if i run:

> pi@openplotter:~ $ sudo apt list | grep node-fetch
> node-fetch/oldstable 1.7.3-1 all

However, on the plugin folder I can find a node-fetch lib v3.x.x (just uninstalled it, so I don't remember the exact version, but if if you need it i'll install again).

**Comment by KEGustafsson** [comment]
Node-fetch v3.x notes says:

"Minimum supported Node.js version is now 12.20"

Can you upgrade to Nodejs v16.x?

**Comment by KEGustafsson** [comment]
Or you could revert couple of codes back to old node-fetch then it should run with nodejs v10.* again.

package.json
`"node-fetch": "^3.1.1"` -> `"node-fetch": "^2.6.0"`

index.js:
`const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));` -> `const fetch = require('node-fetch');`

**Comment by miggat** [comment]
I can't update node because other dependencies, but rolled back the changes as you suggested and now it works perfectly fine.
Thanks!

**Comment by KEGustafsson** [comment]
Good to hear that it worked! I'll close this now.
